In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

In [2]:
filename_train = "../datasets/dataset_apache_train.csv"
filename_test = "../datasets/dataset_apache_test.csv"

In [3]:
csv_test = pd.read_csv(filename_test)
csv_train = pd.read_csv(filename_train)

In [4]:
csv_train.head()

,ip,datetime,gmt,request,status,size,referer,browser,country,detected
0,114.125.221.132,01-Jul 2019 10:54:15,+0700],GET /bkd_baru/assets/images/scan_sertifikat/D0...,200.0,12133,http://universitas.com/bkd_baru/assets/images/...,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA
1,114.125.221.132,01-Jul 2019 10:54:23,+0700],GET /bkd_baru/assets/images/scan_sertifikat/D0...,200.0,15491,http://universitas.com/bkd_baru/assets/images/...,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA
2,114.125.221.132,01-Jul 2019 10:54:42,+0700],POST /bkd_baru/assets/images/scan_sertifikat/D...,200.0,16305,http://universitas.com/bkd_baru/assets/images/...,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA
3,114.125.221.132,01-Jul 2019 10:55:08,+0700],GET /bkd_baru/uwubahon.php HTTP/1.1,404.0,1130,-,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA
4,114.125.221.132,01-Jul 2019 10:55:28,+0700],GET /bkd_baru/awubahon.php HTTP/1.1,200.0,1735,-,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA

In [5]:
csv_test.head()

,IP Address,Date,Time,Request,Status,Size,Referer,User Agent,Lokasi,Status.1
0,36.90.2.19,[23/Jul/2019:09:30:17,+0700],GET /bkd_baru/ HTTP/1.1,200,5198,http://sc.syekhnurjati.ac.id/bkd/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
1,36.90.2.19,[23/Jul/2019:09:30:27,+0700],GET /bkd_baru/home HTTP/1.1,200,18814,http://lpm.syekhnurjati.ac.id/bkd_baru/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
2,36.90.2.19,[23/Jul/2019:09:30:28,+0700],GET /bkd_baru/assets/avatars/icon-user.png HTT...,200,1483,http://lpm.syekhnurjati.ac.id/bkd_baru/home,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
3,36.90.2.19,[23/Jul/2019:09:30:28,+0700],GET /bkd_baru/assets/images/logo/31-05-2019_LO...,200,283099,http://lpm.syekhnurjati.ac.id/bkd_baru/home,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
4,36.90.2.19,[23/Jul/2019:09:30:45,+0700],GET /bkd_baru/bidang_pendidikan HTTP/1.1,200,33678,http://lpm.syekhnurjati.ac.id/bkd_baru/home,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN

In [6]:
csv_test.columns = ["ip", "datetime", "gmt", "request", "status", "size", "referer", "browser", "country", "detected"]

In [7]:
csv_test.head()

,ip,datetime,gmt,request,status,size,referer,browser,country,detected
0,36.90.2.19,[23/Jul/2019:09:30:17,+0700],GET /bkd_baru/ HTTP/1.1,200,5198,http://sc.syekhnurjati.ac.id/bkd/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
1,36.90.2.19,[23/Jul/2019:09:30:27,+0700],GET /bkd_baru/home HTTP/1.1,200,18814,http://lpm.syekhnurjati.ac.id/bkd_baru/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
2,36.90.2.19,[23/Jul/2019:09:30:28,+0700],GET /bkd_baru/assets/avatars/icon-user.png HTT...,200,1483,http://lpm.syekhnurjati.ac.id/bkd_baru/home,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
3,36.90.2.19,[23/Jul/2019:09:30:28,+0700],GET /bkd_baru/assets/images/logo/31-05-2019_LO...,200,283099,http://lpm.syekhnurjati.ac.id/bkd_baru/home,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
4,36.90.2.19,[23/Jul/2019:09:30:45,+0700],GET /bkd_baru/bidang_pendidikan HTTP/1.1,200,33678,http://lpm.syekhnurjati.ac.id/bkd_baru/home,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN

In [8]:
csv_train_split_request = pd.DataFrame()

csv_train_split_request["ip"] = csv_train["ip"]
csv_train_split_request["datetime"] = csv_train["datetime"]
csv_train_split_request["gmt"] = csv_train["gmt"]
csv_train_split_request["request"] = csv_train["request"].str.split(" ").str[0]
csv_train_split_request["content"] = csv_train["request"].str.split(" ").str[1]
csv_train_split_request["status"] = csv_train["status"]
csv_train_split_request["size"] = csv_train["size"]
csv_train_split_request["referer"] = csv_train["referer"]
csv_train_split_request["browser"] = csv_train["browser"]
csv_train_split_request["country"] = csv_train["country"]
csv_train_split_request["detected"] = csv_train["detected"]

csv_train_split_request.head()

,ip,datetime,gmt,request,content,status,size,referer,browser,country,detected
0,114.125.221.132,01-Jul 2019 10:54:15,+0700],GET,/bkd_baru/assets/images/scan_sertifikat/D0001_...,200.0,12133,http://universitas.com/bkd_baru/assets/images/...,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA
1,114.125.221.132,01-Jul 2019 10:54:23,+0700],GET,/bkd_baru/assets/images/scan_sertifikat/D0001_...,200.0,15491,http://universitas.com/bkd_baru/assets/images/...,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA
2,114.125.221.132,01-Jul 2019 10:54:42,+0700],POST,/bkd_baru/assets/images/scan_sertifikat/D0001_...,200.0,16305,http://universitas.com/bkd_baru/assets/images/...,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA
3,114.125.221.132,01-Jul 2019 10:55:08,+0700],GET,/bkd_baru/uwubahon.php,404.0,1130,-,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA
4,114.125.221.132,01-Jul 2019 10:55:28,+0700],GET,/bkd_baru/awubahon.php,200.0,1735,-,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,BAHAYA

In [9]:
csv_test_split_request = pd.DataFrame()

csv_test_split_request["ip"] = csv_test["ip"]
csv_test_split_request["datetime"] = csv_test["datetime"]
csv_test_split_request["gmt"] = csv_test["gmt"]
csv_test_split_request["request"] = csv_test["request"].str.split(" ").str[0]
csv_test_split_request["content"] = csv_test["request"].str.split(" ").str[1]
csv_test_split_request["status"] = csv_test["status"]
csv_test_split_request["size"] = csv_test["size"]
csv_test_split_request["referer"] = csv_test["referer"]
csv_test_split_request["browser"] = csv_test["browser"]
csv_test_split_request["country"] = csv_test["country"]
csv_test_split_request["detected"] = csv_test["detected"]

csv_test_split_request.head()

,ip,datetime,gmt,request,content,status,size,referer,browser,country,detected
0,36.90.2.19,[23/Jul/2019:09:30:17,+0700],GET,/bkd_baru/,200,5198,http://sc.syekhnurjati.ac.id/bkd/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
1,36.90.2.19,[23/Jul/2019:09:30:27,+0700],GET,/bkd_baru/home,200,18814,http://lpm.syekhnurjati.ac.id/bkd_baru/,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
2,36.90.2.19,[23/Jul/2019:09:30:28,+0700],GET,/bkd_baru/assets/avatars/icon-user.png,200,1483,http://lpm.syekhnurjati.ac.id/bkd_baru/home,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
3,36.90.2.19,[23/Jul/2019:09:30:28,+0700],GET,/bkd_baru/assets/images/logo/31-05-2019_LOGO_I...,200,283099,http://lpm.syekhnurjati.ac.id/bkd_baru/home,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN
4,36.90.2.19,[23/Jul/2019:09:30:45,+0700],GET,/bkd_baru/bidang_pendidikan,200,33678,http://lpm.syekhnurjati.ac.id/bkd_baru/home,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,Indonesia,NaN

In [10]:
# replace all NaN values with empty string

csv_train_split_request = csv_train_split_request.fillna("")
csv_test_split_request = csv_test_split_request.fillna("")

In [11]:
from sklearn.preprocessing import LabelEncoder

csv_train_labels_encoded = csv_train_split_request.copy()

le = LabelEncoder()
le.fit(["BAHAYA", "AMAN", "DICURIGAI"])
csv_train_labels_encoded["detected"] = le.transform(csv_train_split_request["detected"])

csv_train_labels_encoded.head()

,ip,datetime,gmt,request,content,status,size,referer,browser,country,detected
0,114.125.221.132,01-Jul 2019 10:54:15,+0700],GET,/bkd_baru/assets/images/scan_sertifikat/D0001_...,200.0,12133,http://universitas.com/bkd_baru/assets/images/...,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,1
1,114.125.221.132,01-Jul 2019 10:54:23,+0700],GET,/bkd_baru/assets/images/scan_sertifikat/D0001_...,200.0,15491,http://universitas.com/bkd_baru/assets/images/...,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,1
2,114.125.221.132,01-Jul 2019 10:54:42,+0700],POST,/bkd_baru/assets/images/scan_sertifikat/D0001_...,200.0,16305,http://universitas.com/bkd_baru/assets/images/...,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,1
3,114.125.221.132,01-Jul 2019 10:55:08,+0700],GET,/bkd_baru/uwubahon.php,404.0,1130,-,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,1
4,114.125.221.132,01-Jul 2019 10:55:28,+0700],GET,/bkd_baru/awubahon.php,200.0,1735,-,Mozilla/5.0 (Linux; Android 5.1.1; SM-J111F Bu...,Indonesia,1

In [12]:
# replace all 2 values with 1

csv_train_labels_encoded["detected"] = csv_train_labels_encoded["detected"].replace(2, 1)
csv_train_labels_encoded["detected"].value_counts()

detected
0    29778
1     7915
Name: count, dtype: int64

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
#vectorize every column

df_vectorized = pd.DataFrame(columns=["ip", "datetime", "gmt", "request", "content", "status", "size", "referer", "browser", "country", "detected"])

codes, uniques = pd.factorize(csv_train_labels_encoded["ip"])
df_vectorized["ip"] = codes

codes, uniques = pd.factorize(csv_train_labels_encoded["datetime"])
df_vectorized["datetime"] = codes

codes, uniques = pd.factorize(csv_train_labels_encoded["gmt"])
df_vectorized["gmt"] = codes

codes, uniques = pd.factorize(csv_train_labels_encoded["request"])
df_vectorized["request"] = codes

codes, uniques = pd.factorize(csv_train_labels_encoded["content"])
df_vectorized["content"] = codes

codes, uniques = pd.factorize(csv_train_split_request["status"].astype(str))
df_vectorized["status"] = codes

codes, uniques = pd.factorize(csv_train_split_request["size"].astype(str))
df_vectorized["size"] = codes


codes, uniques = pd.factorize(csv_train_labels_encoded["referer"])
df_vectorized["referer"] = codes

codes, uniques = pd.factorize(csv_train_labels_encoded["browser"])
df_vectorized["browser"] = codes

codes, uniques = pd.factorize(csv_train_labels_encoded["country"])
df_vectorized["country"] = codes

df_vectorized["detected"] = csv_train_labels_encoded["detected"]

In [15]:
df_vectorized

,ip,datetime,gmt,request,content,status,size,referer,browser,country,detected
0,0,0,0,0,0,0,0,0,0,0,1
1,0,1,0,0,1,0,1,1,0,0,1
2,0,2,0,1,1,0,2,0,0,0,1
3,0,3,0,0,2,1,3,2,0,0,1
4,0,4,0,0,3,0,4,2,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
37688,651,17761,0,0,1789,0,2870,333,69,0,0
37689,651,17762,0,0,2401,0,7015,333,69,0,0
37690,651,17763,0,0,2478,0,3933,333,69,0,0
37691,651,17764,0,0,2483,0,3937,333,69,0,0
37692,651,17765,0,0,1785,0,7017,333,69,0,0

In [16]:
from sklearn.model_selection import train_test_split

data_train, data_test = train_test_split(df_vectorized, test_size=0.3, random_state=42)

## Preparation du dataset pour lentrainment

In [17]:
#remove all detected = 1 from X_train
data_train = data_train[data_train['detected'] != 1]

In [18]:
#remove all detected = 2 from X_train
data_train = data_train[data_train['detected'] != 2]

In [19]:
#verify
data_train['detected'].value_counts()

detected
0    20847
Name: count, dtype: int64

In [20]:
y_train = data_train["detected"].copy()
x_train = data_train.copy()
del x_train["detected"]

In [21]:
print(x_train.head())

        ip  datetime  gmt  request  content  status  size  referer  browser
27946  104     13230    0        0     4046       0  7443      943       75  \
18614  104      8913    0        0       30       0  4806      618       73
20482  104      9735    0        0       91       0  1310       13       76
10581  104      4980    0        0     1717       0  1671      232       65
25483  104     12252    0        0     2532       0  6388      516       89

       country
27946        0
18614        0
20482        0
10581        0
25483        0

In [22]:
print(type(x_train))
print(type(y_train))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [23]:
y_train

27946    0
18614    0
20482    0
10581    0
25483    0
        ..
21962    0
16850    0
6265     0
11284    0
15795    0
Name: detected, Length: 20847, dtype: int64

## Preparation du dataset pour la validation

In [24]:
y_test = data_test["detected"].copy()
x_test = data_test.copy()
del x_test["detected"]

# Evaluation des modeles sans feature selection

## Random Forest

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [26]:
from sklearn.ensemble import IsolationForest

rf_model = IsolationForest()
rf_model.fit(x_train)
anomaly_scores = rf_model.decision_function(x_test)  # Anomaly scores based on proximity measures

In [27]:
anomaly_scores

array([-0.04426915, -0.02395223,  0.05869286, ...,  0.01548745,
        0.03839794,  0.041967  ])

In [28]:
y_pred = np.where(anomaly_scores > 0, 0, 1)
print(classification_report(y_test, y_pred, digits=5))

              precision    recall  f1-score   support

           0    0.81230   0.69197   0.74732      8931
           1    0.25649   0.39924   0.31233      2377

    accuracy                        0.63044     11308
   macro avg    0.53439   0.54561   0.52982     11308
weighted avg    0.69547   0.63044   0.65589     11308

In [29]:
y_pred = np.where(anomaly_scores > -0.2, 0, 1)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      1.00      0.89      8931
           1       0.98      0.04      0.07      2377

    accuracy                           0.80     11308
   macro avg       0.89      0.52      0.48     11308
weighted avg       0.83      0.80      0.71     11308

### maximisation du macro f1

In [30]:
from sklearn.metrics import f1_score

In [31]:
best_threshold = 0
best_macro_f1 = 0

for threshold in np.arange(-0.1, 0.1, 0.001):
    y_pred = np.where(anomaly_scores > threshold, 0, 1)
    macro_f1 = f1_score(y_test, y_pred, average='macro')
    if macro_f1 > best_macro_f1:
        best_macro_f1 = macro_f1
        best_threshold = threshold

print("Best threshold:", best_threshold)
print("Best macro f1:", best_macro_f1)

Best threshold: -0.055999999999999966
Best macro f1: 0.5802559416579961

In [32]:
y_pred = np.where(anomaly_scores > best_threshold, 0, 1)
print(classification_report(y_test, y_pred, digits=5))

              precision    recall  f1-score   support

           0    0.81811   0.89240   0.85364      8931
           1    0.38633   0.25452   0.30687      2377

    accuracy                        0.75831     11308
   macro avg    0.60222   0.57346   0.58026     11308
weighted avg    0.72735   0.75831   0.73871     11308

### maximisation du recall pour 1

In [33]:
from sklearn.metrics import recall_score

In [34]:
best_threshold = 0
best_recall_1 = 0

for threshold in np.arange(-0.1, 0.1, 0.001):
    y_pred = np.where(anomaly_scores > threshold, 0, 1)
    recall_1 = recall_score(y_test, y_pred, pos_label=1)
    if recall_1 > best_recall_1:
        best_recall_1 = recall_1
        best_threshold = threshold


print("Best threshold:", best_threshold)
print("Best recall 1:", best_recall_1)

Best threshold: 0.09900000000000017
Best recall 1: 0.9781236853176273

In [35]:
y_pred = np.where(anomaly_scores > best_threshold, 0, 1)
print(classification_report(y_test, y_pred, digits=5))

              precision    recall  f1-score   support

           0    0.96426   0.15709   0.27017      8931
           1    0.23597   0.97812   0.38021      2377

    accuracy                        0.32968     11308
   macro avg    0.60011   0.56761   0.32519     11308
weighted avg    0.81117   0.32968   0.29330     11308

## One Class SVM

In [36]:
from sklearn.svm import OneClassSVM

In [37]:
clf = OneClassSVM(gamma='auto')
clf.fit(x_train)
anomaly_scores = clf.decision_function(x_test)  # Anomaly scores based on proximity measures

In [38]:
y_pred = np.where(anomaly_scores > -0.6, 0, 1)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.49      0.66      8931
           1       0.34      1.00      0.51      2377

    accuracy                           0.60     11308
   macro avg       0.67      0.75      0.59     11308
weighted avg       0.86      0.60      0.63     11308

In [39]:
best_threshold = 0
best_macro_f1 = 0

for threshold in np.arange(-0.7, -0.5, 0.001):
    y_pred = np.where(anomaly_scores > threshold, 0, 1)
    macro_f1 = f1_score(y_test, y_pred, average='macro')
    if macro_f1 > best_macro_f1:
        best_macro_f1 = macro_f1
        best_threshold = threshold

print("Best threshold:", best_threshold)
print("Best macro f1:", best_macro_f1)

Best threshold: -0.692
Best macro f1: 0.6439891547779082

In [40]:
y_pred = np.where(anomaly_scores > best_threshold, 0, 1)
print(classification_report(y_test, y_pred, digits=5))

              precision    recall  f1-score   support

           0    0.99672   0.57899   0.73249      8931
           1    0.38562   0.99285   0.55549      2377

    accuracy                        0.66599     11308
   macro avg    0.69117   0.78592   0.64399     11308
weighted avg    0.86827   0.66599   0.69528     11308